USEMODULE += iolist
USEPKG += driver_sx126x
FEATURES_REQUIRED += periph_gpio_irq

ifneq (,$(filter netdev,$(USEMODULE)))
USEMODULE += netdev_legacy_api
#USEMODULE += netdev_ieee802154_submac
USEMODULE += lora
endif

ifneq (,$(filter opendsme,$(USEPKG)))
USEMODULE += ztimer_usec
USEMODULE += event_thread
USEMODULE += event_callback
USEMODULE += checksum
endif
