INCLUDES += -I$(RIOTBASE)/pkg/semtech-loramac/include \
            -I$(BINDIRBASE)/pkg/$(BOARD)/semtech-loramac/src/mac \
            -I$(BINDIRBASE)/pkg/$(BOARD)

DIRS += $(RIOTBASE)/pkg/semtech-loramac/contrib
